In [47]:
import requests
import os
import json
from zipfile import ZipFile
import pandas as pd
import geopandas as gpd
from datetime import datetime, timezone, date
from shapely.validation import make_valid
from arcgis.geometry import Geometry

Change this

In [48]:
# May need updating
location = "work"
item_url_file = "ItemURL_ArcGIS_YearlyUpdates.csv" # Can run either "ItemURL_ArcGIS_YearlyUpdates.csv" for yearly updates or "ItemURL_ArcGIS_6monthUpdates.csv" fpr 6 monthly
boundary_file = r"\\192.168.101.45\Projects\Data_team\GIS_data_downloads\CountyBoundary.shp" # Location of file to be used for the data boundary
buffer = 2000 # buffer around boundary (metres)

Should not need updating

In [49]:
if location == "home":
    folder_location = "C:/Users/Lara/Work/DataDownloads"
    download_location = f"{folder_location}/testData"
    
if location == "work":
    folder_location = r"\\192.168.101.45\Projects\Data_team\GIS_data_downloads"
    download_location = r"\\192.168.101.45\gis\GIS_Data\External\Open_Source"

#download_location = "G:/GIS_Data/External/Open_Source/"
temp_download_location = f"{folder_location}/testDataTemp/" # check if still need this
lookup_location = f"{folder_location}/Lookups/"

In [50]:
# Wiltshire boundary for creating Wilts datasets
boundary_gdf = gpd.read_file(boundary_file)
xmin, ymin, xmax, ymax = boundary_gdf.total_bounds

In [51]:
# Read the csv file 
item_url_df = pd.read_csv(lookup_location + item_url_file)
item_url_df.tail(33)

,Dataset,Owner,URL
20,GCN_Risk_Zones_Swindon_and_Wiltshire,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
21,GCN_Strategic_Opportunity_Areas_Swindon_and_Wi...,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
22,Millennium_Greens_Polygons,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
23,National_Character_Areas,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
24,National_Parks,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
25,National_Trails,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
26,Nature_Improvement_Areas,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
27,Nutrient_Neutrality_Catchments,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
28,Organic_Farming_Scheme_Agreements,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
29,Priority_River_Habitat_Headwater_Areas,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
30,Priority_River_Habitat_Rivers,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
31,Provisional_Agricultural_Land_Classification,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
32,Traditional_Orchards_HAP,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
33,Wood_Pasture_and_Parkland,NE,https://services.arcgis.com/JJzESW51TqeY9uat/a...
34,Conservation_Areas,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
35,NHLE_Registered_Parks_and_Gardens,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
36,NHLE_Scheduled_Monuments,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
37,NHLE_Certificate_of_Immunity_polygons,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
38,NHLE_Building_Preservation_Notices_polygons,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
39,NHLE_Listed_Building_polygons,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
40,NHLE_Certificate_of_Immunity_points,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
41,NHLE_Building_Preservation_Notice_points,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
42,NHLE_Listed_Building_points,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
43,NHLE_Protected_Wreck_sites,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
44,NHLE_Registered_Battlefields,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
45,NHLE_World_Heritage_Sites,Historic England,https://services-eu1.arcgis.com/ZOdPfBS3aqqDYP...
46,IBAs_UK,RSPB,https://services1.arcgis.com/h1C9f6qsGKmqXsVs/...
47,RSPB_Priority_Landscapes,RSPB,https://services1.arcgis.com/h1C9f6qsGKmqXsVs/...
48,RSPB_Reserves,RSPB,https://services1.arcgis.com/h1C9f6qsGKmqXsVs/...
49,National_Trust_Open_Data_Land_Always_Open,National Trust,https://services-eu1.arcgis.com/NPIbx47lsIiu2p...
50,National_Trust_Open_Data_Land_Limited_Access,National Trust,https://services-eu1.arcgis.com/NPIbx47lsIiu2p...
51,National_Cycle_Network_Public,Sustrans,https://services5.arcgis.com/1ZHcUS1lwPTg4ms0/...
52,Reclassified_Routes_Public,Sustrans,https://services5.arcgis.com/1ZHcUS1lwPTg4ms0/...

In [52]:
download_list = []

#Loop through each dataset name in lookup
for url in item_url_df.URL:
    print(url)

    # Get dataset name and source from lookup
    dataset = item_url_df[item_url_df.URL==url]['Dataset'].item() 
    dataset = dataset.replace(":", "-")
    source = item_url_df[item_url_df.URL==url]['Owner'].item()

    # Create folder if not already there for permanent data storage
    if not os.path.exists(f"{download_location}/Original/{source}/{dataset}"):
        os.makedirs(f"{download_location}/Original/{source}/{dataset}")
    if not os.path.exists(f"{download_location}/Wiltshire/{source}/{dataset}"):
        os.makedirs(f"{download_location}/Wiltshire/{source}/{dataset}")

     # Download dataset details
     # Get url that contains details for dataset
    url_details = url.replace("/query?", "?f=json")
    try:
        response_details = requests.get(url_details)
        response_details.raise_for_status()
        details = response_details.json()
        date_last_edit = details['editingInfo']['dataLastEditDate']
        dt = datetime.fromtimestamp(date_last_edit / 1000, tz=timezone.utc)
        metadata = {"Date last edited":dt.strftime("%d/%m/%Y"),
                    "Date downloaded":date.today().strftime('%d/%m/%Y')} 
        with open(f"{download_location}/Original/{source}/{dataset}/metadata.json", mode="w") as file:
            json.dump(metadata,file)
        with open(f"{download_location}/Wiltshire/{source}/{dataset}/metadata.json", mode="w") as file:
            json.dump(metadata,file)

        
        max_record_count = details['maxRecordCount']
    except Exception as error:
        print(f"Request failed for details of {dataset}: {error}")

    print(max_record_count)
    # CHeck how many rows should be in dataset
    count_params = {
    "where": "1=1",
    "returnCountOnly": "true",
    "f": "json",
    "outSR": 27700,
    "geometryType":"esriGeometryEnvelope",
    "geometry":json.dumps({"xmin": xmin-buffer, "ymin": ymin-buffer, "xmax": xmax+buffer, "ymax": ymax+buffer}),
    "inSR":27700,
    "spatialRel":"esriSpatialRelIntersects"
    }
    total_count = requests.get(url, params=count_params).json()["count"]

    print("Official feature count:", total_count)

    
    
    
    
    def fetch_page(offset, limit=2000):
        """Fetch a single page of features from ArcGIS FeatureServer."""
        params = {
            "where": "1=1",
            "outFields": "*",
            "returnGeometry": "true",
            "f": "json",
            "outSR": 27700,  # EPSG:27700
            "resultOffset": offset,
            "resultRecordCount": limit,
            "geometryType":"esriGeometryEnvelope",
             "geometry":json.dumps({"xmin": xmin-buffer, "ymin": ymin-buffer, "xmax": xmax+buffer, "ymax": ymax+buffer}),
             "inSR":27700,
             "spatialRel":"esriSpatialRelIntersects"
        }
        return requests.get(url, params=params).json()

    records = []
    geoms = []

    offset = 0
    page_size = max_record_count

    #Keeps running while there is still data to download
    while True:
        print(f"Downloading features {offset} → {offset + page_size} …")
        try:
            data = fetch_page(offset, page_size)
        except Exception as error:
            print(f"Request error occured for {dataset}:", error)   
        feats = data.get("features", [])
        if not feats:
            break
    #extract geom and attributes to convert json to geodataframe  
    # 
 
        for feat in feats:
            attrs = feat.get("attributes", {})
            esri_geom = feat.get("geometry")
            if not esri_geom:
                continue

            try:
                geom = Geometry(esri_geom, sr=27700).as_shapely
                geom = make_valid(geom)  # repair invalid polygons
                if geom.is_empty:
                    continue
            except Exception as e:
                print("Skipping invalid geometry:", e)
                continue

            records.append(attrs)
            geoms.append(geom)

        offset += page_size

    print(f"Downloaded {len(records)} valid features.")
    if len(records) != total_count:
        print("Not all records downloaded")
        full_download = False
    else:
        full_download = True

    # Create GeoDataFrame
    gdf = gpd.GeoDataFrame(records, geometry=geoms, crs="EPSG:27700")

    

    # Remove previous file
    if os.path.exists(f"{download_location}/Original/{source}/{dataset}/{dataset}.gpkg"):
        os.remove(f"{download_location}/Original/{source}/{dataset}/{dataset}.gpkg")

    # Write out original file
    gdf.to_file(f"{download_location}/Original/{source}/{dataset}/{dataset}.gpkg", layer=f"{dataset}", driver="GPKG")
    
    # Clip to Wilts and write out
    if os.path.exists(f"{download_location}/Wiltshire/{source}/{dataset}/{dataset}.gpkg"):
        os.remove(f"{download_location}/Wiltshire/{source}/{dataset}/{dataset}.gpkg")
    gdf_wilts = gpd.clip(gdf, boundary_gdf)
    if gdf_wilts.empty == False:
        gdf_wilts.to_file(f"{download_location}/Wiltshire/{source}/{dataset}/{dataset}.gpkg",layer=f"{dataset}", driver="GPKG")

   
    ## Output info about download to check all downloaded
    row_info = [dataset, source, total_count,len(records),full_download  ]
    download_list.append(row_info)

data_download_df = pd.DataFrame(columns = ["Dataset Title", "Source", "Total features", "Features downloaded", "Complete download?"], data = download_list)

https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Access_Network_Mapping_England/FeatureServer/0/query?
1000
Official feature count: 709
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 709 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Agricultural_Land_Classification_Post_1988/FeatureServer/0/query?
1000
Official feature count: 2439
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloading features 2000 → 3000 …
Downloading features 3000 → 4000 …
Downloaded 2439 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Ancient_Woodland_England/FeatureServer/0/query?
2000
Official feature count: 2403
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloading features 4000 → 6000 …
Downloaded 2403 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Areas_of_Outstanding_Natural_Beauty_England/FeatureServer/0/query?
1000
Official feature count: 3
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 3 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Chalk_Rivers_England/FeatureServer/0/query?
2000
Official feature count: 12340
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloading features 4000 → 6000 …
Downloading features 6000 → 8000 …
Downloading features 8000 → 10000 …
Downloading features 10000 → 12000 …
Downloading features 12000 → 14000 …
Downloading features 14000 → 16000 …
Downloaded 12340 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Conservation_and_Enhancement_Scheme_Agreements_England/FeatureServer/0/query?
1000
Official feature count: 0
Downloading features 0 → 1000 …
Downloaded 0 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Wildlife_Enhancement_Scheme_Agreements_England/FeatureServer/0/query?
100
Official feature count: 3
Downloading features 0 → 100 …
Downloading features 100 → 200 …
Downloaded 3 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Country_Parks_England/FeatureServer/0/query?
1000
Official feature count: 11
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 11 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Countryside_Stewardship_Scheme_2016_Management_Areas_England/FeatureServer/1/query?
1000
Official feature count: 4137
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloading features 2000 → 3000 …
Downloading features 3000 → 4000 …
Downloading features 4000 → 5000 …
Downloading features 5000 → 6000 …
Downloaded 4137 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Countryside_Stewardship_Scheme_2016_Options_England/FeatureServer/1/query?
500
Official feature count: 51740
Downloading features 0 → 500 …
Downloading features 500 → 1000 …
Downloading features 1000 → 1500 …
Downloading features 1500 → 2000 …
Downloading features 2000 → 2500 …
Downloading features 2500 → 3000 …
Downloading features 3000 → 3500 …
Downloading features 3500 → 4000 …
Downloading features 4000 → 4500 …
Downloading features 4500 → 5000 …
Downloading features 5000 → 5500 …
Downloading features 5500 → 6000 …
Downloading features 6000 → 6500 …
Downloading features 6500 → 7000 …
Downloading features 7000 → 7500 …
Downloading features 7500 → 8000 …
Downloading features 8000 → 8500 …
Downloading features 8500 → 9000 …
Downloading features 9000 → 9500 …
Downloading features 9500 → 10000 …
Downloading features 10000 → 10500 …
Downloading features 10500 → 11000 …
Downloading features 11000 → 11500 …
Downloading features 11500 → 12000 …
Downloading features 12000 → 12500 …
Downloading features 12500 → 13000 …
Downloading features 13000 → 13500 …
Downloading features 13500 → 14000 …
Downloading features 14000 → 14500 …
Downloading features 14500 → 15000 …
Downloading features 15000 → 15500 …
Downloading features 15500 → 16000 …
Downloading features 16000 → 16500 …
Downloading features 16500 → 17000 …
Downloading features 17000 → 17500 …
Downloading features 17500 → 18000 …
Downloading features 18000 → 18500 …
Downloading features 18500 → 19000 …
Downloading features 19000 → 19500 …
Downloading features 19500 → 20000 …
Downloading features 20000 → 20500 …
Downloading features 20500 → 21000 …
Downloading features 21000 → 21500 …
Downloading features 21500 → 22000 …
Downloading features 22000 → 22500 …
Downloading features 22500 → 23000 …
Downloading features 23000 → 23500 …
Downloading features 23500 → 24000 …
Downloading features 24000 → 24500 …
Downloading features 24500 → 25000 …
Downloading features 25000 → 25500 …
Downloading features 25500 → 26000 …
Downloading features 26000 → 26500 …
Downloading features 26500 → 27000 …
Downloading features 27000 → 27500 …
Downloading features 27500 → 28000 …
Downloading features 28000 → 28500 …
Downloading features 28500 → 29000 …
Downloading features 29000 → 29500 …
Downloading features 29500 → 30000 …
Downloading features 30000 → 30500 …
Downloading features 30500 → 31000 …
Downloading features 31000 → 31500 …
Downloading features 31500 → 32000 …
Downloading features 32000 → 32500 …
Downloading features 32500 → 33000 …
Downloading features 33000 → 33500 …
Downloading features 33500 → 34000 …
Downloading features 34000 → 34500 …
Downloading features 34500 → 35000 …
Downloading features 35000 → 35500 …
Downloading features 35500 → 36000 …
Downloading features 36000 → 36500 …
Downloading features 36500 → 37000 …
Downloading features 37000 → 37500 …
Downloading features 37500 → 38000 …
Downloading features 38000 → 38500 …
Downloading features 38500 → 39000 …
Downloading features 39000 → 39500 …
Downloading features 39500 → 40000 …
Downloading features 40000 → 40500 …
Downloading features 40500 → 41000 …
Downloading features 41000 → 41500 …
Downloading features 41500 → 42000 …
Downloading features 42000 → 42500 …
Downloading features 42500 → 43000 …
Downloading features 43000 → 43500 …
Downloading features 43500 → 44000 …
Downloading features 44000 → 44500 …
Downloading features 44500 → 45000 …
Downloading features 45000 → 45500 …
Downloading features 45500 → 46000 …
Downloading features 46000 → 46500 …
Downloading features 46500 → 47000 …
Downloading features 47000 → 47500 …
Downloading features 47500 → 48000 …
Downloading features 48000 → 48500 …
Downloading features 48500 → 49000 …
Downloading features 49000 → 49500 …
Downloading features 49500 → 50000 …
Downloading features 50000 → 50500 …
Downloading features 50500 → 51000 …
Downloading features 51000 → 51500 …
Downloading features 51500 → 52000 …
Downloading features 52000 → 52500 …
Downloaded 51740 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/CRoW_Act_2000_Access_Layer/FeatureServer/0/query?
2000
Official feature count: 1355
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 1355 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/CRoW_Act_2000_Section_15_Land/FeatureServer/0/query?
2000
Official feature count: 54
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 54 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/CRoW_Act_2000_Section_16_Dedicated_Land/FeatureServer/0/query?
2000
Official feature count: 18
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 18 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/CRoW_Act_2000_Section_4_Conclusive_Open_Country/FeatureServer/0/query?
2000
Official feature count: 793
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 793 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/CRoW_Act_2000_Section_4_Conclusive_Registered_Common_Land/FeatureServer/0/query?
2000
Official feature count: 645
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 645 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Doorstep_Greens_England/FeatureServer/0/query?
1000
Official feature count: 3
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 3 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Doorstep_Greens_Polygons/FeatureServer/0/query?
1000
Official feature count: 3
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 3 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Environmental_Stewardship_Scheme_Agreements_England_2024/FeatureServer/0/query?
2000
Official feature count: 176
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 176 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Environmental_Stewardship_Scheme_Options/FeatureServer/0/query?
16000
Official feature count: 25387
Downloading features 0 → 16000 …
Downloading features 16000 → 32000 …
Downloading features 32000 → 48000 …
Downloaded 25387 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Environmentally_Sensitive_Area_Scheme_Options/FeatureServer/0/query?
1000
Official feature count: 5367
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloading features 2000 → 3000 …
Downloading features 3000 → 4000 …
Downloading features 4000 → 5000 …
Downloading features 5000 → 6000 …
Downloading features 6000 → 7000 …
Downloaded 5367 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/GCN_Risk_Zones_Swindon_and_Wiltshire/FeatureServer/0/query?
2000
Official feature count: 1050
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 1050 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/GCN_Strategic_Opportunity_Areas_Swindon_and_Wiltshire/FeatureServer/0/query?
2000
Official feature count: 171056
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloading features 4000 → 6000 …
Downloading features 6000 → 8000 …
Downloading features 8000 → 10000 …
Downloading features 10000 → 12000 …
Downloading features 12000 → 14000 …
Downloading features 14000 → 16000 …
Downloading features 16000 → 18000 …
Downloading features 18000 → 20000 …
Downloading features 20000 → 22000 …
Downloading features 22000 → 24000 …
Downloading features 24000 → 26000 …
Downloading features 26000 → 28000 …
Downloading features 28000 → 30000 …
Downloading features 30000 → 32000 …
Downloading features 32000 → 34000 …
Downloading features 34000 → 36000 …
Downloading features 36000 → 38000 …
Downloading features 38000 → 40000 …
Downloading features 40000 → 42000 …
Downloading features 42000 → 44000 …
Downloading features 44000 → 46000 …
Downloading features 46000 → 48000 …
Downloading features 48000 → 50000 …
Downloading features 50000 → 52000 …
Downloading features 52000 → 54000 …
Downloading features 54000 → 56000 …
Downloading features 56000 → 58000 …
Downloading features 58000 → 60000 …
Downloading features 60000 → 62000 …
Downloading features 62000 → 64000 …
Downloading features 64000 → 66000 …
Downloading features 66000 → 68000 …
Downloading features 68000 → 70000 …
Downloading features 70000 → 72000 …
Downloading features 72000 → 74000 …
Downloading features 74000 → 76000 …
Downloading features 76000 → 78000 …
Downloading features 78000 → 80000 …
Downloading features 80000 → 82000 …
Downloading features 82000 → 84000 …
Downloading features 84000 → 86000 …
Downloading features 86000 → 88000 …
Downloading features 88000 → 90000 …
Downloading features 90000 → 92000 …
Downloading features 92000 → 94000 …
Downloading features 94000 → 96000 …
Downloading features 96000 → 98000 …
Downloading features 98000 → 100000 …
Downloading features 100000 → 102000 …
Downloading features 102000 → 104000 …
Downloading features 104000 → 106000 …
Downloading features 106000 → 108000 …
Downloading features 108000 → 110000 …
Downloading features 110000 → 112000 …
Downloading features 112000 → 114000 …
Downloading features 114000 → 116000 …
Downloading features 116000 → 118000 …
Downloading features 118000 → 120000 …
Downloading features 120000 → 122000 …
Downloading features 122000 → 124000 …
Downloading features 124000 → 126000 …
Downloading features 126000 → 128000 …
Downloading features 128000 → 130000 …
Downloading features 130000 → 132000 …
Downloading features 132000 → 134000 …
Downloading features 134000 → 136000 …
Downloading features 136000 → 138000 …
Downloading features 138000 → 140000 …
Downloading features 140000 → 142000 …
Downloading features 142000 → 144000 …
Downloading features 144000 → 146000 …
Downloading features 146000 → 148000 …
Downloading features 148000 → 150000 …
Downloading features 150000 → 152000 …
Downloading features 152000 → 154000 …
Downloading features 154000 → 156000 …
Downloading features 156000 → 158000 …
Downloading features 158000 → 160000 …
Downloading features 160000 → 162000 …
Downloading features 162000 → 164000 …
Downloading features 164000 → 166000 …
Downloading features 166000 → 168000 …
Downloading features 168000 → 170000 …
Downloading features 170000 → 172000 …
Downloading features 172000 → 174000 …
Downloaded 171056 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Millennium_Greens_England_Polygons/FeatureServer/0/query?
1000
Official feature count: 13
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 13 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/National_Character_Areas_England/FeatureServer/0/query?
2000
Official feature count: 17
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 17 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/National_Parks_England/FeatureServer/0/query?
1000
Official feature count: 1
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 1 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/National_Trails_England/FeatureServer/0/query?
1000
Official feature count: 3
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 3 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Nature_Improvement_Areas_England/FeatureServer/0/query?
2000
Official feature count: 1
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 1 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Nutrient_Neutrality_Catchments_England/FeatureServer/0/query?
2000
Official feature count: 4
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 4 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Organic_Farming_Scheme_Agreements/FeatureServer/0/query?
1000
Official feature count: 330
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 330 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Priority_River_Habitat_Headwater_Areas/FeatureServer/0/query?
1000
Official feature count: 34
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 34 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Priority_River_Habitat_Rivers/FeatureServer/0/query?
1000
Official feature count: 419
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 419 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Provisional%20Agricultural%20Land%20Classification%20(ALC)%20(England)/FeatureServer/0/query?
1000
Official feature count: 197
Downloading features 0 → 1000 …
Downloading features 1000 → 2000 …
Downloaded 197 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Traditional_Orchards_HAP_England/FeatureServer/0/query?
2000
Official feature count: 1094
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 1094 valid features.
https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/Wood_Pasture_and_Parkland/FeatureServer/0/query?
2000
Official feature count: 2724
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloading features 4000 → 6000 …
Downloaded 2724 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/Conservation_Areas/FeatureServer/0/query?
2000
Official feature count: 457
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 457 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/7/query?
2000
Official feature count: 96
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 96 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/6/query?
2000
Official feature count: 1750
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 1750 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/5/query?
2000
Official feature count: 2
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 2 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/4/query?
2000
Official feature count: 0
Downloading features 0 → 2000 …
Downloaded 0 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/3/query?
2000
Official feature count: 24913
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloading features 4000 → 6000 …
Downloading features 6000 → 8000 …
Downloading features 8000 → 10000 …
Downloading features 10000 → 12000 …
Downloading features 12000 → 14000 …
Downloading features 14000 → 16000 …
Downloading features 16000 → 18000 …
Downloading features 18000 → 20000 …
Downloading features 20000 → 22000 …
Downloading features 22000 → 24000 …
Downloading features 24000 → 26000 …
Downloading features 26000 → 28000 …
Downloaded 24913 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/2/query?
2000
Official feature count: 2
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloaded 2 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/1/query?
2000
Official feature count: 0
Downloading features 0 → 2000 …
Downloaded 0 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/0/query?
2000
Official feature count: 24911
Downloading features 0 → 2000 …
Downloading features 2000 → 4000 …
Downloading features 4000 → 6000 …
Downloading features 6000 → 8000 …
Downloading features 8000 → 10000 …
Downloading features 10000 → 12000 …
Downloading features 12000 → 14000 …
Downloading features 14000 → 16000 …
Downloading features 16000 → 18000 …
Downloading features 18000 → 20000 …
Downloading features 20000 → 22000 …
Downloading features 22000 → 24000 …
Downloading features 24000 → 26000 …
Downloading features 26000 → 28000 …
Downloaded 24911 valid features.
https://services-eu1.arcgis.com/ZOdPfBS3aqqDYPUQ/arcgis/rest/services/National_Heritage_List_for_England_NHLE_v02_VIEW/FeatureServer/9/query?
2000
Official feature count: 0
Downloading features 0 → 2000 …
Downloaded 0 valid features.

In [53]:
data_download_df.to_csv("../yearly_download_report4.csv")

In [54]:
data_download_df

,Dataset Title,Source,Total features,Features downloaded,Complete download?
0,Access_Network_Mapping,NE,709,709,True
1,Agricultural_Land_Classification_Grades_Post_1...,NE,2439,2439,True
2,Ancient_Woodland,NE,2403,2403,True
3,AONBs_National_Landscapes,NE,3,3,True
4,Chalk_Rivers,NE,12340,12340,True
5,Conservation_and_Enhancement_Scheme_Agreements,NE,0,0,True
6,Wildlife_Enhancement_Scheme_Agreements,NE,3,3,True
7,Country_Parks,NE,11,11,True
8,Countryside_Stewardship_Scheme_2016_Management...,NE,4137,4137,True
9,Countryside_Stewardship_Scheme_2016_Management...,NE,51740,51740,True
10,CRoW_Act_2000_Access_Layer,NE,1355,1355,True
11,CRoW_Act_2000_Section_15_Land,NE,54,54,True
12,CRoW_Act_2000_Section_16_Dedicated_Land,NE,18,18,True
13,CRoW_Act_2000_Section_4_Conclusive_Open_Country,NE,793,793,True
14,CRoW_Act_2000_Section_4_Conclusive_Registered_...,NE,645,645,True
15,Doorstep_Greens_Points,NE,3,3,True
16,Doorstep_Greens_Polygons,NE,3,3,True
17,Environmental_Stewardship_Scheme_Agreements,NE,176,176,True
18,Environmental_Stewardship_Scheme_Options,NE,25387,25387,True
19,Environmentally_Sensitive_Area,NE,5367,5367,True
20,GCN_Risk_Zones_Swindon_and_Wiltshire,NE,1050,1050,True
21,GCN_Strategic_Opportunity_Areas_Swindon_and_Wi...,NE,171056,171056,True
22,Millennium_Greens_Polygons,NE,13,13,True
23,National_Character_Areas,NE,17,17,True
24,National_Parks,NE,1,1,True
25,National_Trails,NE,3,3,True
26,Nature_Improvement_Areas,NE,1,1,True
27,Nutrient_Neutrality_Catchments,NE,4,4,True
28,Organic_Farming_Scheme_Agreements,NE,330,330,True
29,Priority_River_Habitat_Headwater_Areas,NE,34,34,True
30,Priority_River_Habitat_Rivers,NE,419,419,True
31,Provisional_Agricultural_Land_Classification,NE,197,197,True
32,Traditional_Orchards_HAP,NE,1094,1094,True
33,Wood_Pasture_and_Parkland,NE,2724,2724,True
34,Conservation_Areas,Historic England,457,457,True
35,NHLE_Registered_Parks_and_Gardens,Historic England,96,96,True
36,NHLE_Scheduled_Monuments,Historic England,1750,1750,True
37,NHLE_Certificate_of_Immunity_polygons,Historic England,2,2,True
38,NHLE_Building_Preservation_Notices_polygons,Historic England,0,0,True
39,NHLE_Listed_Building_polygons,Historic England,24913,24913,True
40,NHLE_Certificate_of_Immunity_points,Historic England,2,2,True
41,NHLE_Building_Preservation_Notice_points,Historic England,0,0,True
42,NHLE_Listed_Building_points,Historic England,24911,24911,True
43,NHLE_Protected_Wreck_sites,Historic England,0,0,True
44,NHLE_Registered_Battlefields,Historic England,2,2,True
45,NHLE_World_Heritage_Sites,Historic England,2,2,True
46,IBAs_UK,RSPB,4,4,True
47,RSPB_Priority_Landscapes,RSPB,1,1,True
48,RSPB_Reserves,RSPB,6,6,True
49,National_Trust_Open_Data_Land_Always_Open,National Trust,58,58,True
50,National_Trust_Open_Data_Land_Limited_Access,National Trust,25,25,True
51,National_Cycle_Network_Public,Sustrans,873,873,True
52,Reclassified_Routes_Public,Sustrans,39,39,True